/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.ThongKe;

import Models.HD1Month;
import Mysql.ConnectMySql;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author ASUS
 */
public class DL_chart extends javax.swing.JDialog {
    ConnectMySql cn = new ConnectMySql();
    /**
     * Creates new form DL_ThemCaLam
     */
    public DL_chart(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        FillChart();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        jPanel2.setPreferredSize(new java.awt.Dimension(0, 45));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/DeleteRed.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 813, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    private void FillChart() {
        Date date = new Date();
        SimpleDateFormat sf = new SimpleDateFormat("yyyy/MM");
        //xử lysc lấy 6 tháng gần nhất
        Calendar c0 = Calendar.getInstance();
        Calendar c1 = Calendar.getInstance();
        Calendar c2 = Calendar.getInstance();
        Calendar c3 = Calendar.getInstance();
        Calendar c4 = Calendar.getInstance();
        Calendar c5 = Calendar.getInstance();
        ArrayList<HD1Month> ds1 = new ArrayList<HD1Month>(6);
        c0.setTime(date);
        c0.add(Calendar.MONTH,0); 
        Date date0 = c0.getTime();
        HD1Month t1 = new HD1Month();
        t1.setNgay(date0);
//        t1.setTongTien(0);
        
        c1.setTime(date);
        c1.add(Calendar.MONTH, -1);
        Date date1 = c1.getTime();
        HD1Month t2 = new HD1Month();
        t2.setNgay(date1);
//        t2.setTongTien(0);
        
        c2.setTime(date);
        c2.add(Calendar.MONTH, -2);
        Date date2 = c2.getTime();
        HD1Month t3 = new HD1Month();
        t3.setNgay(date2);
//        t3.setTongTien(0);
        
        c3.setTime(date);
        c3.add(Calendar.MONTH, -3); 
        Date date3 = c3.getTime();
        HD1Month t4 = new HD1Month();
        t4.setNgay(date3);
//        t4.setTongTien(0);
        
        c4.setTime(date);
        c4.add(Calendar.MONTH, -4); 
        Date date4 = c4.getTime();
        HD1Month t5 = new HD1Month();
        t5.setNgay(date4);
//        t5.setTongTien(0);
        
        c5.setTime(date);
        c5.add(Calendar.MONTH, -5); 
        Date date5 = c5.getTime();
        HD1Month t6 = new HD1Month();
        t6.setNgay(date5);
//        t6.setTongTien(0);
        
        ds1.add(t6);
        ds1.add(t5);
        ds1.add(t4);
        ds1.add(t3);
        ds1.add(t2);
        ds1.add(t1);
        
        ArrayList<HD1Month> ds = new ArrayList<>();
        ds = cn.GetHDThang();
        if(ds != null){
            for(HD1Month i : ds){
                for(HD1Month j : ds1){
                    if(sf.format(i.getNgay()).equals(sf.format(j.getNgay()))){
                        j.setTongTien(j.getTongTien()+i.getTongTien());
                    }
                }
            }
        }else{
            System.out.println("có gì đâu");
        }
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();       
        for(HD1Month j : ds1){
            dataset.setValue(j.getTongTien(), "Tổng tiền", sf.format(j.getNgay()));
        }
        
        JFreeChart jchart = ChartFactory.createBarChart("Tổng thu nhập 6 tháng gần nhất", "Tháng", "Tổng thu", dataset, PlotOrientation.VERTICAL, true, true, false);
        CategoryPlot plot = jchart.getCategoryPlot();
        plot.setRangeGridlinePaint(Color.black);
        plot.setRangeZeroBaselinePaint(Color.white);
        ChartPanel panel = new ChartPanel(jchart);
        jPanel1.removeAll();
        jPanel1.add(panel);
        jPanel1.updateUI();
    }
}
