/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.QuanLy;

import Interface.BanHang.Banhang_UI;
import Interface.Run;
import Models.Ban;
import Models.KhuVuc;
import Mysql.ConnectMySql;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author ASUS
 */
public class QL_Ban extends javax.swing.JPanel {
    ConnectMySql cn = new ConnectMySql();
    /**
     * Creates new form QL_Ban
     */
    public static QL_Ban B;
    public QL_Ban() {
        B = this;
        initComponents();
        FillKV();
        FillBan();
        setFontTable(tbBan);
        setFontTable(tbKhuVuc);
    }

     private void setFontTable(JTable t){
        Font myFont = new Font("Serif", Font.PLAIN, 16);
        JTableHeader hd1 = t.getTableHeader();
        hd1.setFont(myFont);
    }
    public void FillKV() {
        ArrayList<KhuVuc> arrTable = cn.GetAllKhuVuc();
        DefaultTableModel tbmodel = new DefaultTableModel();
 
        tbmodel.addColumn("Mã khu vực");
        tbmodel.addColumn("Tên khu vực");
        
        if (arrTable != null) {
            int sokv = 0;
            for (KhuVuc kv : arrTable) {
                sokv++;
                tbmodel.addRow(new Object[]{kv.getMaKhuVuc(), kv.getTenKhuVuc()});
            }
            lblkhuvuc.setText(String.valueOf(sokv)+" khu vực");
        } else {
            JOptionPane.showMessageDialog(null, "Không có khu vực nào");
        }
        tbKhuVuc.setModel(tbmodel);
        for(int i = 0; i < tbKhuVuc.getColumnCount();i++){
            Class<?> col = tbKhuVuc.getColumnClass(i);
            tbKhuVuc.setDefaultEditor(col, null);
        }        
    }
    
    public void FillBan() {
        ArrayList<Ban> arrTable = cn.GetAllBan();
        ArrayList<KhuVuc> arrKV = cn.GetAllKhuVuc();
        DefaultTableModel tbmodel = new DefaultTableModel();
        
        tbmodel.addColumn("Mã Bàn");
        tbmodel.addColumn("Mã khu vực");        
        tbmodel.addColumn("Khu vực");

        tbmodel.addColumn("Tên bàn");
        tbmodel.addColumn("Trạng thái");
        
        if (arrTable != null) {
            int soban = 0;
            for (Ban b : arrTable) {
                soban++;
                for (KhuVuc k : arrKV){
                    if(b.getMaKhuVuc()==k.getMaKhuVuc()){
                tbmodel.addRow(new Object[]{b.GetMaBan(), b.getMaKhuVuc(),k.getTenKhuVuc(), b.GetTenBan(), b.GetTrangThai()});
                    }
                }
            }
            lblthongtin.setText(String.valueOf(soban)+" bàn");
        } else {
            JOptionPane.showMessageDialog(null, "Không có bàn nào");
        }
        tbBan.setModel(tbmodel);
        for(int i = 0; i < tbBan.getColumnCount();i++){
            Class<?> col = tbBan.getColumnClass(i);
            tbBan.setDefaultEditor(col, null);
        }        
        
        tbBan.getColumnModel().getColumn(0).setMinWidth(0);
        tbBan.getColumnModel().getColumn(0).setMaxWidth(0);        
        tbBan.getColumnModel().getColumn(0).setPreferredWidth(0);

        tbBan.getColumnModel().getColumn(1).setMinWidth(0);
        tbBan.getColumnModel().getColumn(1).setMaxWidth(0);
        tbBan.getColumnModel().getColumn(1).setPreferredWidth(0);
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbBan = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txttim = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lblthongtin = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbKhuVuc = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        lblkhuvuc = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnThemKV = new javax.swing.JButton();
        btnSuaKV = new javax.swing.JButton();
        btnXoaKV = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnThemBan = new javax.swing.JButton();
        btnSuaBan = new javax.swing.JButton();
        btnXoaBan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1150, 740));
        setPreferredSize(new java.awt.Dimension(1150, 740));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bàn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 1, 20))); // NOI18N

        jScrollPane1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N

        tbBan.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        tbBan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Bàn", "Mã Khu vực", "Tên khu vực", "Tên bàn", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbBan.setRowHeight(25);
        tbBan.setSelectionBackground(new java.awt.Color(0, 255, 204));
        jScrollPane1.setViewportView(tbBan);
        if (tbBan.getColumnModel().getColumnCount() > 0) {
            tbBan.getColumnModel().getColumn(0).setMinWidth(0);
            tbBan.getColumnModel().getColumn(0).setPreferredWidth(0);
            tbBan.getColumnModel().getColumn(0).setMaxWidth(0);
            tbBan.getColumnModel().getColumn(1).setMinWidth(0);
            tbBan.getColumnModel().getColumn(1).setPreferredWidth(0);
            tbBan.getColumnModel().getColumn(1).setMaxWidth(0);
        }

        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel3.setText("Tìm bàn : ");

        txttim.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        txttim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txttimKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel6.setText("Tổng số bàn :");

        lblthongtin.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lblthongtin.setForeground(new java.awt.Color(255, 0, 0));
        lblthongtin.setText("...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txttim, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblthongtin)
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txttim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblthongtin))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Khu vực", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 1, 20))); // NOI18N

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));

        tbKhuVuc.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        tbKhuVuc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Mã Khu vực", "Tên Khu vực"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbKhuVuc.setMinimumSize(new java.awt.Dimension(20, 20));
        tbKhuVuc.setRowHeight(25);
        tbKhuVuc.setSelectionBackground(new java.awt.Color(0, 255, 204));
        jScrollPane3.setViewportView(tbKhuVuc);
        if (tbKhuVuc.getColumnModel().getColumnCount() > 0) {
            tbKhuVuc.getColumnModel().getColumn(0).setMinWidth(0);
            tbKhuVuc.getColumnModel().getColumn(0).setPreferredWidth(0);
            tbKhuVuc.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel4.setText("Tổng số KV :");

        lblkhuvuc.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lblkhuvuc.setForeground(new java.awt.Color(255, 0, 0));
        lblkhuvuc.setText("...");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblkhuvuc)
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblkhuvuc))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btnThemKV.setBackground(new java.awt.Color(255, 255, 255));
        btnThemKV.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        btnThemKV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_add_30px.png"))); // NOI18N
        btnThemKV.setText("Thêm KV");
        btnThemKV.setPreferredSize(new java.awt.Dimension(111, 47));
        btnThemKV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemKVActionPerformed(evt);
            }
        });

        btnSuaKV.setBackground(new java.awt.Color(255, 255, 255));
        btnSuaKV.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        btnSuaKV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_edit_file_30px.png"))); // NOI18N
        btnSuaKV.setText("Sửa KV");
        btnSuaKV.setPreferredSize(new java.awt.Dimension(111, 47));
        btnSuaKV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaKVActionPerformed(evt);
            }
        });

        btnXoaKV.setBackground(new java.awt.Color(255, 255, 255));
        btnXoaKV.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        btnXoaKV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_cancel_35px.png"))); // NOI18N
        btnXoaKV.setText("Xóa KV");
        btnXoaKV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaKVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnThemKV, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(btnSuaKV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoaKV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnThemKV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnSuaKV, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnXoaKV)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        btnThemBan.setBackground(new java.awt.Color(255, 255, 255));
        btnThemBan.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        btnThemBan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_add_30px.png"))); // NOI18N
        btnThemBan.setText("Thêm Bàn");
        btnThemBan.setPreferredSize(new java.awt.Dimension(111, 47));
        btnThemBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemBanActionPerformed(evt);
            }
        });

        btnSuaBan.setBackground(new java.awt.Color(255, 255, 255));
        btnSuaBan.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        btnSuaBan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_edit_file_30px.png"))); // NOI18N
        btnSuaBan.setText("Sửa Bàn");
        btnSuaBan.setPreferredSize(new java.awt.Dimension(111, 47));
        btnSuaBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaBanActionPerformed(evt);
            }
        });

        btnXoaBan.setBackground(new java.awt.Color(255, 255, 255));
        btnXoaBan.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        btnXoaBan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_cancel_35px.png"))); // NOI18N
        btnXoaBan.setText("Xóa Bàn");
        btnXoaBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaBanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnThemBan, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(btnSuaBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoaBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnThemBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnSuaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnXoaBan)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Quản lý bàn, khu vực");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(366, 366, 366)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(136, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemKVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemKVActionPerformed
        DL_ThemKV kv = new DL_ThemKV(Run.menuQL, true);
        kv.setVisible(true);
    }//GEN-LAST:event_btnThemKVActionPerformed

    private void btnSuaKVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaKVActionPerformed
        int select=tbKhuVuc.getSelectedRow();
        if(select<0){
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn khu vực nào !");
        }else{
            int MaKV = (int) tbKhuVuc.getValueAt(select, 0);
            DL_SuaKV sua = new DL_SuaKV(Run.menuQL, true, MaKV);
            sua.setVisible(true);
        }
    }//GEN-LAST:event_btnSuaKVActionPerformed

    private void btnXoaKVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaKVActionPerformed
        int[] selectedRows = tbKhuVuc.getSelectedRows();

        if (selectedRows.length <= 0) {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn khu vực nào !");
        } else {
            ArrayList<Integer> ListMaKV = new ArrayList<Integer>();
            String sp = "";
            for (int i : selectedRows) {
                int ma = (int) tbKhuVuc.getValueAt(i, 0);
                ListMaKV.add(ma);
                String tenkv= (String) tbKhuVuc.getValueAt(i, 1);

                sp += tenkv + "\n";
            }
            int qs;
            qs = JOptionPane.showConfirmDialog(null, "Xóa Khu vực: \n " + sp, "Xóa khu vực", JOptionPane.YES_NO_OPTION);
            if (qs == JOptionPane.YES_OPTION) {
                boolean xoaban = cn.DeleteBanMaKV(ListMaKV);
                boolean xoa = cn.DeleteKV(ListMaKV);

                if (xoa == true && xoaban == true) {
                    QL_Ban.B.FillKV();
                    QL_Ban.B.updateUI();
                    try{
                        Banhang_UI.bh.loadKhuVuc();
                    }catch(Exception e){
                        
                    }
                }else
                    JOptionPane.showMessageDialog(null, "Không xóa được khu vực, vui lòng xóa hết bàn trong khu vực này!");

            }
        }
    }//GEN-LAST:event_btnXoaKVActionPerformed

    private void btnThemBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemBanActionPerformed
        DL_ThemBan kv = new DL_ThemBan(Run.menuQL, true);
        kv.setVisible(true);
    }//GEN-LAST:event_btnThemBanActionPerformed

    private void btnSuaBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaBanActionPerformed
       int select=tbBan.getSelectedRow();
        if(select<0){
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn bàn nào !");
        }else{
            int MaBan = (int) tbBan.getValueAt(select, 0);
            DL_SuaBan sua = new DL_SuaBan(Run.menuQL, true, MaBan);
            sua.setVisible(true);
        }
    }//GEN-LAST:event_btnSuaBanActionPerformed

    private void btnXoaBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaBanActionPerformed
        int[] selectedRows = tbBan.getSelectedRows();

        if (selectedRows.length <= 0) {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn bàn nào !");
        } else {
            ArrayList<Integer> ListMaBan = new ArrayList<Integer>();
            String sp = "";
            for (int i : selectedRows) {
                int ma = (int) tbBan.getValueAt(i, 0);
                ListMaBan.add(ma);
                String tenban = (String) tbBan.getValueAt(i, 3);

                sp += tenban + "\n";
            }
            int qs;
            qs = JOptionPane.showConfirmDialog(null, "Xóa bàn: \n " + sp, "Xóa bàn", JOptionPane.YES_NO_OPTION);
            if (qs == JOptionPane.YES_OPTION) {
                boolean xoa = cn.DeleteBan(ListMaBan);

                if (xoa == true) {
                    QL_Ban.B.FillBan();
                    QL_Ban.B.updateUI();

                }else
                    JOptionPane.showMessageDialog(null, "Không xóa được bàn !");

            }
        }
    }//GEN-LAST:event_btnXoaBanActionPerformed

    private void txttimKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttimKeyReleased
        ArrayList<Ban> arrTable = cn.SearchBan(txttim.getText());
        if(arrTable != null){
            DefaultTableModel tbmodel = new DefaultTableModel();

            tbmodel.addColumn("Mã Bàn");
            tbmodel.addColumn("Tên bàn");
            tbmodel.addColumn("Trạng thái");

            int soban = 0;
            for (Ban b : arrTable) {
                soban++;
                tbmodel.addRow(new Object[]{b.GetMaBan(), b.GetTenBan(), b.GetTrangThai()});
            }
            lblthongtin.setText(String.valueOf(soban)+" bàn");
            tbBan.setModel(tbmodel);
            for(int i = 0; i < tbBan.getColumnCount();i++){
                Class<?> col = tbBan.getColumnClass(i);
                tbBan.setDefaultEditor(col, null);
            }
        }
    }//GEN-LAST:event_txttimKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSuaBan;
    private javax.swing.JButton btnSuaKV;
    private javax.swing.JButton btnThemBan;
    private javax.swing.JButton btnThemKV;
    private javax.swing.JButton btnXoaBan;
    private javax.swing.JButton btnXoaKV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblkhuvuc;
    private javax.swing.JLabel lblthongtin;
    private javax.swing.JTable tbBan;
    private javax.swing.JTable tbKhuVuc;
    private javax.swing.JTextField txttim;
    // End of variables declaration//GEN-END:variables
}
